### ISSUE TITLE
Implementar o modelo do objeto "Restaurant"

### ISSUE THREAD

**Issue by auroralimin** [scartezini/ES012017#40]
- Implementar um objeto contendo: 
    - id: String
    - name: String
    - email: String 
    - address: String
    - number: String
    - cnpj: String
    - website: String
    - password: String

[[User Story] Cadastrar um restaurante](https://github.com/scartezini/ES012017/projects/2)

**Comment by rafaelmartinsrm** [comment]
Alem disso seria interessante avaliar a possibilidade de inserir aqui a senha do usuário para login, @riheldo.
